# Generated by Django 4.2 on 2023-06-14 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_article_last_updated_alter_article_author_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='ContactMessage',
        ),
        migrations.RemoveField(
            model_name='article',
            name='last_updated',
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
