# Generated by Django 4.2 on 2023-06-14 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0008_delete_contact_delete_contactmessage_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialLink',
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
